--
-- PostgreSQL database dump
--

\restrict 7cZp28ql1c7C61RqLkZAyxubS0TezUUJgJnpugzYJi20EpOnAx9m4jX23wbSDOD

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-04-14 18:30:22

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 222 (class 1259 OID 16518)
-- Name: components; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.components (
    component_id integer NOT NULL,
    component_name character varying NOT NULL
);


ALTER TABLE public.components OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16477)
-- Name: events; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.events (
    event_id integer NOT NULL,
    event_template character varying NOT NULL
);


ALTER TABLE public.events OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16486)
-- Name: logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.logs (
    log_id integer NOT NULL,
    log_date timestamp without time zone NOT NULL,
    log_pid integer NOT NULL,
    log_content character varying NOT NULL,
    event_id integer NOT NULL,
    component_id integer NOT NULL
);


ALTER TABLE public.logs OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16509)
-- Name: logs_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.logs ALTER COLUMN log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.logs_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4921 (class 0 OID 16518)
-- Dependencies: 222
-- Data for Name: components; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.components (component_id, component_name) FROM stdin;
1	LabSZ
2	Other
\.


--
-- TOC entry 4918 (class 0 OID 16477)
-- Dependencies: 219
-- Data for Name: events; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.events (event_id, event_template) FROM stdin;
1	Accepted password for (.*) from (.*) port (.*) ssh2
3	Did not receive identification string from (.*)
8	Failed none for invalid user (.*) from (.*) port (.*) ssh2
9	Failed password for (.*) from (.*) port (.*) ssh2
10	Failed password for invalid user (.*) from (.*) port (.*) ssh2
13	Invalid user (.*) from (.*)
15	PAM (.*) more authentication failure; logname= uid=(.*) euid=(.*) tty=ssh ruser= rhost=(.*)
16	PAM (.*) more authentication failures; logname= uid=(.*) euid=(.*) tty=ssh ruser= rhost=(.*)
17	PAM (.*) more authentication failures; logname= uid=(.*) euid=(.*) tty=ssh ruser= rhost=(.*) user=root
26	Received disconnect from (.*): (.*): disconnected by user
2	Connection closed by (.*) \\[preauth\\]
4	Disconnecting: Too many authentication failures for admin \\[preauth\\]
5	Disconnecting: Too many authentication failures for root \\[preauth\\]
6	error: Received disconnect from (.*): (.*): com.jcraft.jsch.JSchException: Auth fail \\[preauth\\]
7	error: Received disconnect from (.*): (.*): No more user authentication methods available. \\[preauth\\]
11	fatal: Write failed: Connection reset by peer \\[preauth\\]
12	input_userauth_request: invalid user (.*) \\[preauth\\]
14	message repeated (.*) times: \\[ Failed password for root from (.*) port (.*)\\]
24	Received disconnect from (.*): (.*): Bye Bye \\[preauth\\]
25	Received disconnect from (.*): (.*): Closed due to user request. \\[preauth\\]
27	reverse mapping checking getaddrinfo for (.*) \\[(.*)\\] failed - POSSIBLE BREAK-IN ATTEMPT!
18	PAM service\\(sshd\\) ignoring max retries; (.*) > (.*)
19	pam_unix\\(sshd:auth\\): authentication failure; logname= uid=(.*) euid=(.*) tty=ssh ruser= rhost=(.*)
20	pam_unix\\(sshd:auth\\): authentication failure; logname= uid=(.*) euid=(.*) tty=ssh ruser= rhost=(.*) user=(.*)
21	pam_unix\\(sshd:auth\\): check pass; user unknown
22	pam_unix\\(sshd:session\\): session closed for user (.*)
23	pam_unix\\(sshd:session\\): session opened for user (.*) by (uid=(.*))
28	Other
\.


--
-- TOC entry 4919 (class 0 OID 16486)
-- Dependencies: 220
-- Data for Name: logs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.logs (log_id, log_date, log_pid, log_content, event_id, component_id) FROM stdin;
\.


--
-- TOC entry 4927 (class 0 OID 0)
-- Dependencies: 221
-- Name: logs_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.logs_log_id_seq', 1, false);


--
-- TOC entry 4768 (class 2606 OID 16525)
-- Name: components components_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.components
    ADD CONSTRAINT components_pk PRIMARY KEY (component_id);


--
-- TOC entry 4764 (class 2606 OID 16485)
-- Name: events events_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pk PRIMARY KEY (event_id);


--
-- TOC entry 4766 (class 2606 OID 16498)
-- Name: logs logs_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.logs
    ADD CONSTRAINT logs_pk PRIMARY KEY (log_id);


--
-- TOC entry 4769 (class 2606 OID 16527)
-- Name: logs logs_components_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.logs
    ADD CONSTRAINT logs_components_fk FOREIGN KEY (component_id) REFERENCES public.components(component_id);


--
-- TOC entry 4770 (class 2606 OID 16504)
-- Name: logs logs_events_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.logs
    ADD CONSTRAINT logs_events_fk FOREIGN KEY (event_id) REFERENCES public.events(event_id);


-- Completed on 2026-04-14 18:30:22

--
-- PostgreSQL database dump complete
--

\unrestrict 7cZp28ql1c7C61RqLkZAyxubS0TezUUJgJnpugzYJi20EpOnAx9m4jX23wbSDOD

